@echo off
setlocal enabledelayedexpansion

:INPUT_LOOP
set "player="
set /p "player=Please enter your Minecraft player name: "

:: Check characters with PowerShell (3 to 16 characters, A-Z a-z 0-9 _ only)
powershell -NoLogo -NoProfile -Command "try { if (-not [string]::IsNullOrEmpty('%player%') -and '%player%'.Length -ge 3 -and '%player%'.Length -le 16 -and '%player%' -match '^[A-Za-z0-9_]+$') { exit 0 } else { exit 1 } } catch { exit 1 }" 2>nul
if errorlevel 1 (
    rem Invalid name. Must be 3-16 characters, only A-Z, a-z, 0-9 and _ are allowed.
    goto INPUT_LOOP
)

:: Get UUID and Name from Mojang API (safely handles special characters)
set "line="
for /f "delims=" %%A in ('powershell -NoLogo -NoProfile -Command "try { $player='%player%'; $r=Invoke-RestMethod ('https://api.mojang.com/users/profiles/minecraft/' + $player) -ErrorAction Stop; if ($r -ne $null) { Write-Output ($r.id.Trim() + ';' + $r.name.Trim()) } } catch {}"') do (
    set "line=%%A"
)

:: Existence determination
if not defined line (
    echo.
    echo   Username %player% does not exist.
    goto :eof
)

:: Decompose id;name
for /f "tokens=1* delims=;" %%i in ("%line%") do (
    set "uuid=%%i"
    set "name=%%j"
)

:: Format the UUID with hyphens
set "u1=!uuid:~0,8!"
set "u2=!uuid:~8,4!"
set "u3=!uuid:~12,4!"
set "u4=!uuid:~16,4!"
set "u5=!uuid:~20,12!"
set "uuid_hyphen=!u1!-!u2!-!u3!-!u4!-!u5!"

echo.
echo   Username !name! ^(UUID: !uuid_hyphen!^) exists.

exit /b

::Description
rem This script checks a Minecraft player's name and UUID
rem Currently, you cannot specify the player name as an argument, but this may be possible in the future.

rem These codes were generated by ChatGPT